name: Build Oraxen Jar

on:
  push:
    branches: [ "master", "main" ] # Si attiva ogni volta che fai una modifica
  workflow_dispatch: # Questo ti permette di far partire la compilazione a mano con un tasto!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew build -x test # Compila saltando i test per fare prima

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Oraxen-Jar
        # Questa riga ora cerca ricorsivamente in tutto il progetto i file .jar
        path: "**/build/libs/*.jar" 
        # Escludiamo i file inutili per non fare confusione
        if-no-files-found: error
